- name: set hostname
  ansible.builtin.hostname:
    name: ec2-13-60-169-125.eu-north-1.compute.amazonaws.com
    use: systemd

- name: localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 localhost.localdomain localhost

- name: ec2-13-61-35-135.eu-north-1.compute.amazonaws.com
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 13.60.169.125 ec2-13-60-169-125.eu-north-1.compute.amazonaws.com
