---
galaxy_info:
  author: Your Name
  description: Ansible role to deploy Prometheus monitoring system
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
    - name: EL
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - monitoring
    - prometheus
    - metrics
    - observability

dependencies: []