- name: install packages
  community.general.pacman:
    update_cache: yes
    name:
      - certbot
      - certbot-dns-linode
    state: present

- name: certbot
  ansible.builtin.copy:
    src: certbot
    dest: /root/
    owner: root
    group: root
    mode: "700"


- name: ensure certbot-renew.timer is started and enabled at boot
  ansible.builtin.systemd:
    name: certbot-renew.timer
    state: started
    enabled: yes

#- name: run get-certs
#  command: "/root/certbot/get-certs.sh"


- name: Run certbot with verbose output for debugging
  ansible.builtin.command:
    cmd: /root/certbot/get-certs.sh
  register: certbot_result
  failed_when: false
  become: yes

- name: Display detailed certbot output
  ansible.builtin.debug:
    var: certbot_result
