---
galaxy_info:
  author: Your Name
  description: Ansible role for configuring Prometheus Alertmanager
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
    - name: RedHat
      versions:
        - 7
        - 8
        - 9
  galaxy_tags:
    - prometheus
    - alertmanager
    - monitoring
    - alerting

dependencies: []